# 使用 Node.js 16 作为基础镜像
FROM node:16-alpine

# 设置工作目录
WORKDIR /app

# 复制 package.json 和 package-lock.json
COPY package.json package-lock.json ./

# 安装依赖
RUN npm install --production

# 复制应用代码
COPY . ./

# 暴露端口
EXPOSE 3003

# 启动应用
CMD ["node", "server.js"]